name = "mcp-memory-server"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "PATH=$HOME/.nvm/versions/node/v22.16.0/bin:$PATH /snap/bin/bun install --ignore-scripts"

[dev]
port = 8787
